Server:
  app_name: Admin GOGO
  port: :5000
  db_driver: pgx

# postgresql://postgres:xiaohuozhi@localhost:5432/tengfeiliang?sslmode=disable
DataBase:
  path: localhost
  port: 5432
  username: postgres
  password: postgres
  db_name: postgres
  max_idle_conns: 5
  max_open_conns: 100

Auth:
  token_symmetric_key: knUEpyxhNyVX7ZivGAGsRARmwJ5qGFog
  access_token_duration: 1440m
  refresh_token_duration: 10080m

Logger:
  level: debug
  path: ./logs
  max_size: 1
  max_age: 30

Redis:
  address: 127.0.0.1:6379
  db: 1
  password: